import { pgTable, uuid, varchar, text, timestamp, date, integer, boolean, pgEnum } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';

// Enums
export const userRoleEnum = pgEnum('user_role', ['admin', 'teacher', 'parent']);
export const developmentScopeEnum = pgEnum('development_scope', [
  'religious_moral',
  'physical_motor',
  'cognitive',
  'language',
  'social_emotional',
  'art'
]);
export const assessmentScoreEnum = pgEnum('assessment_score', ['BB', 'MB', 'BSH', 'BSB']);

// Tables
export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name'),
  email: varchar('email').unique(),
  passwordHash: varchar('password_hash'),
  role: userRoleEnum('role'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
});

export const classrooms = pgTable('classrooms', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name'),
  academicYear: varchar('academic_year'),
  teacherId: uuid('teacher_id').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const students = pgTable('students', {
  id: uuid('id').primaryKey().defaultRandom(),
  fullName: varchar('full_name'),
  classroomId: uuid('classroom_id').references(() => classrooms.id),
  birthDate: date('birth_date'),
  gender: varchar('gender'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const parentChild = pgTable('parent_child', {
  id: uuid('id').primaryKey().defaultRandom(),
  parentId: uuid('parent_id').references(() => users.id),
  childId: uuid('child_id').references(() => students.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const activityAgenda = pgTable('activity_agenda', {
  id: uuid('id').primaryKey().defaultRandom(),
  date: date('date'),
  classroomId: uuid('classroom_id').references(() => classrooms.id),
  description: text('description'),
  createdBy: uuid('created_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const developmentScopes = pgTable('development_scopes', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: developmentScopeEnum('name'),
});

export const learningObjectives = pgTable('learning_objectives', {
  id: uuid('id').primaryKey().defaultRandom(),
  scopeId: uuid('scope_id').references(() => developmentScopes.id),
  description: text('description'),
});

export const dailyAssessments = pgTable('daily_assessments', {
  id: uuid('id').primaryKey().defaultRandom(),
  date: date('date'),
  studentId: uuid('student_id').references(() => students.id),
  teacherId: uuid('teacher_id').references(() => users.id),
  scopeId: uuid('scope_id').references(() => developmentScopes.id),
  objectiveId: uuid('objective_id').references(() => learningObjectives.id),
  activityContext: text('activity_context'),
  score: assessmentScoreEnum('score'),
  note: text('note'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const lessonPlans = pgTable('lesson_plans', {
  id: uuid('id').primaryKey().defaultRandom(),
  classroomId: uuid('classroom_id').references(() => classrooms.id),
  date: date('date'),
  generatedByAi: boolean('generated_by_ai'),
  content: text('content'),
  createdBy: uuid('created_by').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const weeklyReports = pgTable('weekly_reports', {
  id: uuid('id').primaryKey().defaultRandom(),
  studentId: uuid('student_id').references(() => students.id),
  weekStart: date('week_start'),
  weekEnd: date('week_end'),
  summaryText: text('summary_text'),
  autoGenerated: boolean('auto_generated'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

export const monthlyReports = pgTable('monthly_reports', {
  id: uuid('id').primaryKey().defaultRandom(),
  studentId: uuid('student_id').references(() => students.id),
  month: integer('month'),
  year: integer('year'),
  summaryText: text('summary_text'),
  autoGenerated: boolean('auto_generated'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
});

// Relations
export const usersRelations = relations(users, ({ many }) => ({
  classrooms: many(classrooms),
  parentChildren: many(parentChild),
  activityAgenda: many(activityAgenda),
  lessonPlans: many(lessonPlans),
  dailyAssessments: many(dailyAssessments),
}));

export const classroomsRelations = relations(classrooms, ({ one, many }) => ({
  teacher: one(users, {
    fields: [classrooms.teacherId],
    references: [users.id],
  }),
  students: many(students),
  activityAgenda: many(activityAgenda),
  lessonPlans: many(lessonPlans),
}));

export const studentsRelations = relations(students, ({ one, many }) => ({
  classroom: one(classrooms, {
    fields: [students.classroomId],
    references: [classrooms.id],
  }),
  parentChildren: many(parentChild),
  dailyAssessments: many(dailyAssessments),
  weeklyReports: many(weeklyReports),
  monthlyReports: many(monthlyReports),
}));

export const parentChildRelations = relations(parentChild, ({ one }) => ({
  parent: one(users, {
    fields: [parentChild.parentId],
    references: [users.id],
  }),
  child: one(students, {
    fields: [parentChild.childId],
    references: [students.id],
  }),
}));

export const developmentScopesRelations = relations(developmentScopes, ({ many }) => ({
  learningObjectives: many(learningObjectives),
  dailyAssessments: many(dailyAssessments),
}));

export const learningObjectivesRelations = relations(learningObjectives, ({ one, many }) => ({
  scope: one(developmentScopes, {
    fields: [learningObjectives.scopeId],
    references: [developmentScopes.id],
  }),
  dailyAssessments: many(dailyAssessments),
}));

export const dailyAssessmentsRelations = relations(dailyAssessments, ({ one }) => ({
  student: one(students, {
    fields: [dailyAssessments.studentId],
    references: [students.id],
  }),
  teacher: one(users, {
    fields: [dailyAssessments.teacherId],
    references: [users.id],
  }),
  scope: one(developmentScopes, {
    fields: [dailyAssessments.scopeId],
    references: [developmentScopes.id],
  }),
  objective: one(learningObjectives, {
    fields: [dailyAssessments.objectiveId],
    references: [learningObjectives.id],
  }),
}));
