'use client'

import { useState, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import { PageHeader } from '@/components/layout/page-header'
import { LoadingState } from '@/components/layout/loading-state'
import { WeeklyReportCard } from '@/components/report/weekly-report-card'
import { useCurrentUser } from '@/lib/hooks/use-current-user'
import { IconChartBar, IconHome, IconLoader2 } from '@tabler/icons-react'
import { Card, CardContent } from '@/components/ui/card'

interface WeeklyReport {
  id: string
  studentId: string | null
  weekStart: string | null
  weekEnd: string | null
  summaryText: string | null
  autoGenerated: boolean | null
  isPublished: boolean | null
  createdAt: Date | null
}

export default function ParentWeeklyReportPage() {
  const router = useRouter()
  const params = useParams<{ childId: string }>()
  const { user, children, loading: userLoading } = useCurrentUser()
  const [reports, setReports] = useState<WeeklyReport[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!userLoading && !user) router.push('/auth/login')
    if (!userLoading && user && user.role !== 'parent') router.push('/unauthorized')
  }, [user, userLoading, router])

  useEffect(() => {
    if (!params.childId || userLoading) return
    setLoading(true)
    fetch(`/api/reports/weekly?studentId=${params.childId}`)
      .then((r) => r.json())
      .then((data) => {
        if (data.error) setError(data.error)
        else setReports(data.data ?? [])
      })
      .catch(() => setError('Terjadi kesalahan'))
      .finally(() => setLoading(false))
  }, [params.childId, userLoading])

  if (userLoading) return <LoadingState message="Memuat data..." />
  if (!user) return null

  const child = children?.find((c) => c.id === params.childId)
  const childName = child?.fullName ?? 'Anak'

  return (
    <div className="space-y-6">
      <PageHeader
        title="Laporan Mingguan"
        description={childName}
        breadcrumbs={[
          { label: 'Beranda', href: '/parent', icon: IconHome },
          { label: 'Laporan', href: '/parent/report', icon: IconChartBar },
          { label: childName, href: `/parent/report/${params.childId}` },
          { label: 'Mingguan' },
        ]}
      />

      {loading && (
        <div className="flex items-center justify-center py-12 gap-2 text-muted-foreground">
          <IconLoader2 className="animate-spin" size={20} />
          <span>Memuat laporan...</span>
        </div>
      )}

      {error && (
        <Card>
          <CardContent className="py-6 text-center text-destructive">{error}</CardContent>
        </Card>
      )}

      {!loading && !error && reports.length === 0 && (
        <Card>
          <CardContent className="py-10 text-center text-muted-foreground">
            Belum ada laporan mingguan yang tersedia.
          </CardContent>
        </Card>
      )}

      {!loading && !error && reports.length > 0 && (
        <div className="space-y-4">
          {reports.map((report) => (
            <WeeklyReportCard
              key={report.id}
              weekStart={report.weekStart}
              weekEnd={report.weekEnd}
              summaryText={report.summaryText}
              createdAt={report.createdAt}
            />
          ))}
        </div>
      )}
    </div>
  )
}
