'use client'

import { useState, useEffect, useRef, useCallback } from 'react'
import { useRouter, useParams } from 'next/navigation'
import { PageHeader } from '@/components/layout/page-header'
import { LoadingState } from '@/components/layout/loading-state'
import { ScoreRadarChart } from '@/components/report/score-radar-chart'
import { MoodLineChart } from '@/components/report/mood-line-chart'
import { WeeklyAssessmentDetail } from '@/components/report/weekly-assessment-detail'
import { ActivityGallery } from '@/components/report/activity-gallery'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import {
  IconChartBar,
  IconHome,
  IconArrowLeft,
  IconPrinter,
  IconFileTypePdf,
  IconPencil,
  IconCheck,
  IconLoader2,
  IconSparkles,
  IconEye,
  IconEyeOff,
  IconBrandWhatsapp,
  IconCalendar,
  IconBook,
  IconUsers,
} from '@tabler/icons-react'

// ── Types ────────────────────────────────────────────────────────────────────

interface WeeklyReport {
  id: string
  studentId: string | null
  weekStart: string | null
  weekEnd: string | null
  summaryText: string | null
  autoGenerated: boolean | null
  isPublished: boolean | null
  createdAt: Date | null
}

interface StudentInfo {
  id: string
  fullName: string | null
  birthDate: string | null
  gender: string | null
  classroomId: string | null
}

interface TopicsPayload {
  semester: { title: string; academicYear: string | null; semesterNumber: number | null } | null
  monthly: { title: string; monthNumber: number | null } | null
  weekly: { title: string; weekNumber: number | null } | null
}

interface AttendanceDay {
  date: string
  checkIn: { status: string | null; mood: string | null } | null
  checkOut: { status: string | null; mood: string | null } | null
}

interface ScopeScores {
  [scope: string]: { BB: number; MB: number; BSH: number; BSB: number; total: number }
}

interface MoodTimeSeriesItem {
  date: string
  checkIn: string | null
  checkOut: string | null
}

interface ScopeBreakdown {
  scope: string
  objectives: {
    objectiveId: string | null
    objectiveDescription: string | null
    entries: {
      date: string | null
      activityContext: string | null
      score: string | null
      note: string | null
    }[]
  }[]
}

interface ActivityImage {
  date: string | null
  imageUrl: string | null
}

interface DetailPayload {
  report: WeeklyReport
  student: StudentInfo | null
  topics: TopicsPayload | null
  attendanceByDate: AttendanceDay[]
  scopeScores: ScopeScores
  moodTimeSeries: MoodTimeSeriesItem[]
  scopeBreakdown: ScopeBreakdown[]
  activityImages: ActivityImage[]
}

// ── Utils ────────────────────────────────────────────────────────────────────

const MOOD_LABELS: Record<string, string> = {
  bahagia: '😊 Bahagia',
  sedih: '😢 Sedih',
  marah: '😠 Marah',
  takut: '😨 Takut',
  jijik: '🤢 Jijik',
}

const STATUS_LABELS: Record<string, string> = {
  present: 'Hadir',
  sick: 'Sakit',
  permission: 'Izin',
}

const STATUS_COLORS: Record<string, string> = {
  present: 'bg-green-100 text-green-700',
  sick: 'bg-red-100 text-red-700',
  permission: 'bg-yellow-100 text-yellow-700',
}

const MONTH_NAMES = [
  'Januari','Februari','Maret','April','Mei','Juni',
  'Juli','Agustus','September','Oktober','November','Desember',
]

// ── Main component ───────────────────────────────────────────────────────────

export default function WeeklyReportDetailClient() {
  const router = useRouter()
  const params = useParams<{ id: string }>()
  const reportId = params.id

  const [payload, setPayload] = useState<DetailPayload | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  // Edit state
  const [isEditing, setIsEditing] = useState(false)
  const [summaryText, setSummaryText] = useState('')
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)

  // AI regenerate
  const [generating, setGenerating] = useState(false)

  // Publish state
  const [showPublishConfirm, setShowPublishConfirm] = useState(false)
  const [publishing, setPublishing] = useState(false)

  // PDF export
  const [exporting, setExporting] = useState(false)
  const printRef = useRef<HTMLDivElement>(null)

  const fetchDetail = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await fetch(`/api/reports/weekly/${reportId}/detail`)
      if (!res.ok) {
        const j = await res.json()
        throw new Error(j.error ?? 'Gagal memuat laporan')
      }
      const json = await res.json()
      const data: DetailPayload = json.data
      setPayload(data)
      setSummaryText(data.report.summaryText ?? '')
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Terjadi kesalahan')
    } finally {
      setLoading(false)
    }
  }, [reportId])

  useEffect(() => {
    fetchDetail()
  }, [fetchDetail])

  const handleSave = async () => {
    if (!payload) return
    setSaving(true)
    try {
      const res = await fetch(`/api/reports/weekly/${reportId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ summaryText }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error)
      setPayload((p) => p ? { ...p, report: json.data } : p)
      setSaved(true)
      setTimeout(() => setSaved(false), 2000)
      setIsEditing(false)
    } catch (e) {
      console.error(e)
    } finally {
      setSaving(false)
    }
  }

  const handleGenerateAI = async () => {
    if (!payload) return
    setGenerating(true)
    try {
      const res = await fetch('/api/reports/weekly/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          studentId: payload.report.studentId,
          weekStart: payload.report.weekStart,
          weekEnd: payload.report.weekEnd,
        }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error)
      setSummaryText(json.summary)
      setIsEditing(true)
    } catch (e) {
      console.error(e)
    } finally {
      setGenerating(false)
    }
  }

  const handlePublishToggle = async () => {
    if (!payload) return
    setPublishing(true)
    try {
      const newPublished = !payload.report.isPublished
      const res = await fetch(`/api/reports/weekly/${reportId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isPublished: newPublished }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error)
      setPayload((p) => p ? { ...p, report: json.data } : p)
    } catch (e) {
      console.error(e)
    } finally {
      setPublishing(false)
      setShowPublishConfirm(false)
    }
  }

  const handlePrint = () => {
    window.print()
  }

  const handleExportPDF = async () => {
    if (!printRef.current || !payload) return
    setExporting(true)

    // The app shell has `body { overflow: hidden; h-screen }` and
    // `main { overflow-y: auto; h-full }`. html2canvas respects these
    // constraints and only captures the visible viewport portion.
    // Temporarily remove them so the full element height is captured.
    const bodyEl = document.body
    const mainEl = document.querySelector('main') as HTMLElement | null
    const prevBodyOverflow = bodyEl.style.overflow
    const prevBodyHeight = bodyEl.style.height
    const prevMainOverflow = mainEl?.style.overflow ?? ''
    const prevMainOverflowY = mainEl?.style.overflowY ?? ''
    const prevMainHeight = mainEl?.style.height ?? ''

    bodyEl.style.overflow = 'visible'
    bodyEl.style.height = 'auto'
    if (mainEl) {
      mainEl.style.overflow = 'visible'
      mainEl.style.overflowY = 'visible'
      mainEl.style.height = 'auto'
    }

    try {
      const html2canvas = (await import('html2canvas')).default
      const { jsPDF } = await import('jspdf')

      // html2canvas 1.x cannot parse CSS Color Level 4 functions (oklch, lab,
      // lch, color-mix) used by Tailwind v4. Strategy:
      //   1. Strip those functions from every <style> tag in the clone so the
      //      parser never sees them.
      //   2. Inject hex-value overrides for all Tailwind custom properties so
      //      the rendered output still gets correct colours.
      const onclone = (_clonedDoc: Document, clonedEl: HTMLElement) => {
        const doc = clonedEl.ownerDocument

        // Step 1 — remove unsupported color functions from cloned stylesheets
        doc.querySelectorAll('style').forEach(el => {
          if (!el.textContent) return
          el.textContent = el.textContent
            .replace(/:\s*oklch\([^;{}]+\)/g, ': transparent')
            .replace(/:\s*lab\([^;{}]+\)/g, ': transparent')
            .replace(/:\s*lch\([^;{}]+\)/g, ': transparent')
            .replace(/:\s*color-mix\([^;{}]+\)/g, ': transparent')
        })

        // Step 2 — inject proper hex values for every Tailwind CSS variable
        const style = doc.createElement('style')
        style.textContent = `
          :root {
            --background: #f9f9fe !important;
            --foreground: #292933 !important;
            --card: #ffffff !important;
            --card-foreground: #292933 !important;
            --popover: #ffffff !important;
            --popover-foreground: #292933 !important;
            --primary-foreground: #fcfcfc !important;
            --secondary-foreground: #292933 !important;
            --muted: #f3f3f8 !important;
            --muted-foreground: #737382 !important;
            --accent-foreground: #fcfcfc !important;
            --destructive: #db4141 !important;
            --border: #e3e3e9 !important;
            --input: #eeeef5 !important;
            --ring: #3f52b2 !important;
            --chart-1: #3f52b2 !important;
            --chart-2: #3d8aaa !important;
            --chart-3: #46aa6b !important;
            --chart-4: #2a9b95 !important;
            --chart-5: #58b88d !important;
            --sidebar: #3f52b2 !important;
            --sidebar-foreground: #fcfcfc !important;
            --sidebar-primary: #46aa6b !important;
            --sidebar-primary-foreground: #fcfcfc !important;
            --sidebar-accent: #4d5fc2 !important;
            --sidebar-accent-foreground: #fcfcfc !important;
            --sidebar-border: #2d40a0 !important;
            --sidebar-ring: #46aa6b !important;
          }
        `
        doc.head.appendChild(style)
      }

      const canvas = await html2canvas(printRef.current, {
        scale: 2,
        useCORS: true,
        logging: false,
        scrollX: 0,
        scrollY: 0,
        windowWidth: printRef.current.scrollWidth,
        windowHeight: printRef.current.scrollHeight,
        onclone,
      })

      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      const pdfWidth = pdf.internal.pageSize.getWidth()
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width

      let heightLeft = pdfHeight
      let position = 0
      const pageHeight = pdf.internal.pageSize.getHeight()

      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight)
      heightLeft -= pageHeight

      while (heightLeft > 0) {
        position -= pageHeight
        pdf.addPage()
        pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight)
        heightLeft -= pageHeight
      }

      const studentName = payload.student?.fullName?.replace(/\s+/g, '_') ?? 'siswa'
      pdf.save(`laporan_mingguan_${studentName}_${payload.report.weekStart}.pdf`)
    } catch (e) {
      console.error('PDF export failed:', e)
    } finally {
      // Restore app-shell overflow constraints
      bodyEl.style.overflow = prevBodyOverflow
      bodyEl.style.height = prevBodyHeight
      if (mainEl) {
        mainEl.style.overflow = prevMainOverflow
        mainEl.style.overflowY = prevMainOverflowY
        mainEl.style.height = prevMainHeight
      }
      setExporting(false)
    }
  }

  if (loading) return <LoadingState message="Memuat laporan..." />
  if (error) {
    return (
      <div className="py-16 text-center space-y-4">
        <p className="text-destructive">{error}</p>
        <Button variant="outline" onClick={() => router.back()}>
          <IconArrowLeft size={16} className="mr-2" />
          Kembali
        </Button>
      </div>
    )
  }
  if (!payload) return null

  const { report, student, topics, attendanceByDate, scopeScores, moodTimeSeries, scopeBreakdown, activityImages } = payload

  const isPublished = report.isPublished ?? false
  const monthName = topics?.monthly?.monthNumber
    ? MONTH_NAMES[(topics.monthly.monthNumber - 1) % 12]
    : null

  return (
    <div className="space-y-6">
      {/* Breadcrumb + action bar (hidden on print) */}
      <div className="print:hidden print-hidden">
        <PageHeader
          title={`Laporan Mingguan — ${student?.fullName ?? '—'}`}
          description={`${report.weekStart} – ${report.weekEnd}`}
          breadcrumbs={[
            { label: 'Beranda', href: '/teacher', icon: IconHome },
            { label: 'Laporan', href: '/teacher/report', icon: IconChartBar },
            { label: 'Laporan Mingguan', href: '/teacher/report/weekly' },
            { label: student?.fullName ?? '—' },
          ]}
        />

        {/* Action bar */}
        <div className="flex items-center gap-2 flex-wrap mt-4">
          <Button variant="outline" size="sm" onClick={() => router.back()} className="gap-1.5">
            <IconArrowLeft size={15} />
            Kembali
          </Button>

          <Button variant="outline" size="sm" onClick={handlePrint} className="gap-1.5">
            <IconPrinter size={15} />
            Print
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={handleExportPDF}
            disabled={exporting}
            className="gap-1.5"
          >
            {exporting ? (
              <IconLoader2 size={15} className="animate-spin" />
            ) : (
              <IconFileTypePdf size={15} />
            )}
            Export PDF
          </Button>

          <Button
            variant="outline"
            size="sm"
            onClick={handleGenerateAI}
            disabled={generating}
            className="gap-1.5"
          >
            {generating ? (
              <IconLoader2 size={15} className="animate-spin" />
            ) : (
              <IconSparkles size={15} />
            )}
            Regenerate AI
          </Button>

          {isEditing ? (
            <Button size="sm" onClick={handleSave} disabled={saving} className="gap-1.5">
              {saving ? (
                <IconLoader2 size={15} className="animate-spin" />
              ) : saved ? (
                <IconCheck size={15} />
              ) : (
                <IconPencil size={15} />
              )}
              Simpan
            </Button>
          ) : (
            <Button
              variant="outline"
              size="sm"
              onClick={() => setIsEditing(true)}
              className="gap-1.5"
            >
              <IconPencil size={15} />
              Edit Ringkasan
            </Button>
          )}

          {/* Publish toggle */}
          <Button
            variant={isPublished ? 'default' : 'outline'}
            size="sm"
            onClick={() => setShowPublishConfirm(true)}
            disabled={publishing}
            className="gap-1.5"
          >
            {publishing ? (
              <IconLoader2 size={15} className="animate-spin" />
            ) : isPublished ? (
              <IconEye size={15} />
            ) : (
              <IconEyeOff size={15} />
            )}
            {isPublished ? 'Terbit' : 'Draf'}
          </Button>

          {/* TODO: integrate WhatsApp Business API for parent notification */}
          <Button variant="outline" size="sm" disabled className="gap-1.5 opacity-50 cursor-not-allowed" title="Fitur pengiriman WhatsApp akan tersedia dalam pembaruan mendatang">
            <IconBrandWhatsapp size={15} />
            Kirim WhatsApp
          </Button>
        </div>
      </div>

      {/* ── Printable content ───────────────────────────────────────────── */}
      <div ref={printRef} id="weekly-report-print" className="space-y-6">

        {/* Print-only header */}
        <div className="hidden print:block text-center py-4 border-b-2">
          <p className="text-sm text-muted-foreground">Laporan Perkembangan Mingguan</p>
          <h1 className="text-xl font-bold mt-1">{student?.fullName ?? '—'}</h1>
          <p className="text-sm mt-0.5">{report.weekStart} – {report.weekEnd}</p>
        </div>

        {/* 1. Topik ──────────────────────────────────────────────────────── */}
        <Card>
          <CardHeader className="border-b">
            <CardTitle className="flex items-center gap-2 text-base">
              <IconBook size={18} />
              Topik Pembelajaran
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            {!topics ? (
              <p className="text-sm text-muted-foreground italic">Topik belum dikonfigurasi untuk periode ini</p>
            ) : (
              <table className="w-full text-sm">
                <tbody className="divide-y">
                  {topics.semester && (
                    <tr>
                      <td className="py-2 pr-4 text-muted-foreground w-32 font-medium">Semester</td>
                      <td className="py-2">
                        {topics.semester.title}
                        {topics.semester.semesterNumber && (
                          <span className="ml-2 text-xs text-muted-foreground">
                            (Semester {topics.semester.semesterNumber}, TA {topics.semester.academicYear})
                          </span>
                        )}
                      </td>
                    </tr>
                  )}
                  {topics.monthly && (
                    <tr>
                      <td className="py-2 pr-4 text-muted-foreground font-medium">Bulanan</td>
                      <td className="py-2">
                        {topics.monthly.title}
                        {monthName && (
                          <span className="ml-2 text-xs text-muted-foreground">({monthName})</span>
                        )}
                      </td>
                    </tr>
                  )}
                  {topics.weekly && (
                    <tr>
                      <td className="py-2 pr-4 text-muted-foreground font-medium">Mingguan</td>
                      <td className="py-2">
                        {topics.weekly.title}
                        {topics.weekly.weekNumber && (
                          <span className="ml-2 text-xs text-muted-foreground">
                            (Minggu {topics.weekly.weekNumber})
                          </span>
                        )}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            )}
          </CardContent>
        </Card>

        {/* 2. Rekap Kehadiran ────────────────────────────────────────────── */}
        <Card>
          <CardHeader className="border-b">
            <CardTitle className="flex items-center gap-2 text-base">
              <IconCalendar size={18} />
              Rekap Kehadiran
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4">
            {attendanceByDate.length === 0 ? (
              <p className="text-sm text-muted-foreground">Tidak ada data kehadiran pada periode ini</p>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b text-muted-foreground text-xs">
                      <th className="text-left py-2 pr-4 font-medium">Tanggal</th>
                      <th className="text-left py-2 pr-4 font-medium">Status</th>
                      <th className="text-left py-2 pr-4 font-medium">Mood Check-in</th>
                      <th className="text-left py-2 font-medium">Mood Check-out</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    {attendanceByDate.map((day) => (
                      <tr key={day.date}>
                        <td className="py-2 pr-4 tabular-nums">
                          {new Date(day.date).toLocaleDateString('id-ID', {
                            weekday: 'short',
                            day: 'numeric',
                            month: 'short',
                          })}
                        </td>
                        <td className="py-2 pr-4">
                          {day.checkIn?.status ? (
                            <Badge
                              variant="outline"
                              className={`text-xs ${STATUS_COLORS[day.checkIn.status] ?? ''}`}
                            >
                              {STATUS_LABELS[day.checkIn.status] ?? day.checkIn.status}
                            </Badge>
                          ) : (
                            <span className="text-muted-foreground text-xs">—</span>
                          )}
                        </td>
                        <td className="py-2 pr-4 text-sm">
                          {day.checkIn?.mood
                            ? MOOD_LABELS[day.checkIn.mood] ?? day.checkIn.mood
                            : <span className="text-muted-foreground">—</span>}
                        </td>
                        <td className="py-2 text-sm">
                          {day.checkOut?.mood
                            ? MOOD_LABELS[day.checkOut.mood] ?? day.checkOut.mood
                            : <span className="text-muted-foreground">—</span>}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </CardContent>
        </Card>

        {/* 3 & 4. Charts ─────────────────────────────────────────────────── */}
        <div className="grid gap-4 lg:grid-cols-2 print:grid-cols-1">
          <ScoreRadarChart scopeScores={scopeScores} />
          <MoodLineChart moodTimeSeries={moodTimeSeries} />
        </div>

        {/* 5. Ringkasan Pencapaian ────────────────────────────────────────── */}
        <WeeklyAssessmentDetail scopeBreakdown={scopeBreakdown} />

        {/* 6. Galeri Aktivitas ────────────────────────────────────────────── */}
        <ActivityGallery images={activityImages} />

        {/* 7. Ringkasan ────────────────────────────────────────────────────── */}
        <Card>
          <CardHeader className="border-b">
            <CardTitle className="flex items-center gap-2 text-base justify-between">
              <span className="flex items-center gap-2">
                <IconUsers size={18} />
                Ringkasan Pencapaian Mingguan
              </span>
              <div className="flex items-center gap-2 print:hidden">
                {report.autoGenerated && (
                  <Badge variant="secondary" className="gap-1 text-[10px]">
                    <IconSparkles size={10} />
                    AI
                  </Badge>
                )}
                <Badge variant={isPublished ? 'default' : 'outline'} className="text-xs">
                  {isPublished ? 'Terbit' : 'Draf'}
                </Badge>
              </div>
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-4 space-y-3">
            {isEditing ? (
              <>
                <Textarea
                  value={summaryText}
                  onChange={(e) => setSummaryText(e.target.value)}
                  rows={10}
                  placeholder="Tulis ringkasan perkembangan mingguan siswa..."
                  className="text-sm"
                />
                <div className="flex gap-2 print:hidden">
                  <Button size="sm" onClick={handleSave} disabled={saving} className="gap-1.5">
                    {saving ? (
                      <IconLoader2 size={14} className="animate-spin" />
                    ) : (
                      <IconCheck size={14} />
                    )}
                    Simpan
                  </Button>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      setIsEditing(false)
                      setSummaryText(report.summaryText ?? '')
                    }}
                  >
                    Batal
                  </Button>
                </div>
              </>
            ) : (
              <div className="space-y-3">
                {report.summaryText ? (
                  <p className="text-sm leading-relaxed whitespace-pre-wrap">{report.summaryText}</p>
                ) : (
                  <p className="text-sm text-muted-foreground italic">
                    Belum ada ringkasan. Klik &quot;Edit Ringkasan&quot; atau &quot;Regenerate AI&quot; untuk membuat.
                  </p>
                )}
              </div>
            )}
          </CardContent>
        </Card>

        {/* Print footer */}
        <div className="hidden print:block text-center text-xs text-muted-foreground border-t pt-4 mt-4">
          Dicetak dari sistem jurnal harian TK · {new Date().toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}
        </div>
      </div>

      {/* Publish confirm dialog */}
      <AlertDialog open={showPublishConfirm} onOpenChange={setShowPublishConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              {isPublished ? 'Tarik dari publikasi?' : 'Publikasikan laporan?'}
            </AlertDialogTitle>
            <AlertDialogDescription>
              {isPublished
                ? 'Laporan tidak akan terlihat lagi oleh orang tua.'
                : 'Laporan akan terlihat oleh orang tua siswa.'}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Batal</AlertDialogCancel>
            <AlertDialogAction onClick={handlePublishToggle}>
              {isPublished ? 'Tarik' : 'Terbitkan'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}
