'use client'

import {
  useReactTable,
  getCoreRowModel,
  flexRender,
  type ColumnDef,
} from '@tanstack/react-table'
import { useRouter } from 'next/navigation'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import { IconEye, IconTrash, IconRobot, IconDownload, IconSend, IconSendOff } from '@tabler/icons-react'
import Link from 'next/link'

export interface WeeklyReportRow {
  id: string
  studentId: string | null
  studentName: string | null
  weekStart: string | null
  weekEnd: string | null
  summaryText: string | null
  autoGenerated: boolean | null
  isPublished: boolean | null
  pdfUrl: string | null
  sentAt: Date | string | null
  createdAt: Date | null
}

interface WeeklyReportTableProps {
  data: WeeklyReportRow[]
  onDelete: (id: string) => void
  onSend: (id: string) => Promise<void>
  sending?: Set<string>
}

export function WeeklyReportTable({ data, onDelete, onSend, sending = new Set() }: WeeklyReportTableProps) {
  const router = useRouter()

  // Rows eligible for bulk send: published but not yet sent
  const bulkable = data.filter((r) => r.isPublished && !r.sentAt)

  const columns: ColumnDef<WeeklyReportRow>[] = [
    {
      accessorKey: 'studentName',
      header: 'Siswa',
      cell: ({ row }) => (
        <Link className="text-sm text-primary" href={`/teacher/report/weekly/${row.original.id}`}>
          {row.original.studentName || <em>—</em>}
        </Link>
      ),
    },
    {
      id: 'period',
      header: 'Periode',
      cell: ({ row }) => (
        <span className="text-sm tabular-nums">
          {row.original.weekStart} – {row.original.weekEnd}
        </span>
      ),
    },
    {
      id: 'status',
      header: 'Status',
      cell: ({ row }) => (
        <div className="flex items-center gap-1.5">
          <Badge variant={row.original.isPublished ? 'default' : 'outline'}>
            {row.original.isPublished ? 'Terbit' : 'Draf'}
          </Badge>
          {row.original.autoGenerated && (
            <Badge variant="secondary" className="gap-1 text-[10px]">
              <IconRobot size={10} />
              AI
            </Badge>
          )}
        </div>
      ),
    },
    {
      id: 'sent',
      header: 'Terkirim',
      cell: ({ row }) => {
        const sentAt = row.original.sentAt
        if (!sentAt) {
          return <span className="text-xs text-muted-foreground">Belum dikirim</span>
        }
        const d = new Date(sentAt)
        return (
          <span className="text-xs tabular-nums text-green-700">
            {d.toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' })}
          </span>
        )
      },
    },
    {
      id: 'actions',
      header: '',
      cell: ({ row }) => {
        const r = row.original
        const isSending = sending.has(r.id)
        const canSend = !!r.isPublished
        return (
          <div className="flex items-center justify-end gap-1">
            {r.pdfUrl && (
              <Button variant="ghost" size="icon" className="h-8 w-8" title="Unduh PDF" asChild>
                <a href={r.pdfUrl} target="_blank" rel="noopener noreferrer">
                  <IconDownload size={16} />
                </a>
              </Button>
            )}
            <Button
              variant="ghost"
              size="icon"
              className="h-8 w-8"
              onClick={() => router.push(`/teacher/report/weekly/${r.id}`)}
              title="Lihat laporan"
            >
              <IconEye size={16} />
            </Button>

            {/* Send to parent */}
            <TooltipProvider delayDuration={200}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <span>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-8 w-8"
                      disabled={!canSend || isSending || !!r.sentAt}
                      onClick={() => onSend(r.id)}
                      title="Kirim ke orang tua"
                    >
                      {isSending ? (
                        <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
                      ) : r.sentAt ? (
                        <IconSendOff size={16} className="text-green-600" />
                      ) : (
                        <IconSend size={16} className={canSend ? '' : 'opacity-40'} />
                      )}
                    </Button>
                  </span>
                </TooltipTrigger>
                <TooltipContent side="top">
                  {!canSend
                    ? 'Terbitkan laporan sebelum mengirim'
                    : r.sentAt
                    ? 'Sudah dikirim ke orang tua'
                    : 'Kirim ke orang tua'}
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>

            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive hover:text-destructive" title="Hapus laporan">
                  <IconTrash size={16} />
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Hapus laporan?</AlertDialogTitle>
                  <AlertDialogDescription>
                    Laporan minggu {r.weekStart} – {r.weekEnd} untuk{' '}
                    <strong>{r.studentName}</strong> akan dihapus permanen.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Batal</AlertDialogCancel>
                  <AlertDialogAction
                    className="bg-destructive hover:bg-destructive/90"
                    onClick={() => onDelete(r.id)}
                  >
                    Hapus
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>
        )
      },
    },
  ]

  const table = useReactTable({
    data,
    columns,
    getCoreRowModel: getCoreRowModel(),
  })

  if (data.length === 0) {
    return (
      <div className="rounded-sm border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Siswa</TableHead>
              <TableHead>Periode</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Terkirim</TableHead>
              <TableHead />
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell colSpan={5} className="text-center py-12 text-muted-foreground">
                Belum ada laporan untuk periode ini
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    )
  }

  return (
    <div className="space-y-2">
      {/* Bulk send bar */}
      {bulkable.length > 0 && (
        <div className="flex items-center justify-between rounded-sm border bg-muted/40 px-3 py-2">
          <span className="text-sm text-muted-foreground">
            <strong>{bulkable.length}</strong> laporan terbit belum dikirim
          </span>
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button size="sm" className="gap-2">
                <IconSend size={14} />
                Kirim Semua ke Orang Tua
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Kirim semua laporan?</AlertDialogTitle>
                <AlertDialogDescription>
                  {bulkable.length} laporan yang sudah terbit akan dikirimkan ke orang tua
                  masing-masing siswa.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Batal</AlertDialogCancel>
                <AlertDialogAction
                  onClick={() => bulkable.forEach((r) => onSend(r.id))}
                  className="gap-2"
                >
                  <IconSend size={14} />
                  Kirim Semua
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      )}

      <div className="rounded-sm border">
        <Table>
          <TableHeader>
            {table.getHeaderGroups().map((hg) => (
              <TableRow key={hg.id}>
                {hg.headers.map((h) => (
                  <TableHead key={h.id}>
                    {flexRender(h.column.columnDef.header, h.getContext())}
                  </TableHead>
                ))}
              </TableRow>
            ))}
          </TableHeader>
          <TableBody>
            {table.getRowModel().rows.map((row) => (
              <TableRow key={row.id} className="cursor-pointer hover:bg-muted/40">
                {row.getVisibleCells().map((cell) => (
                  <TableCell key={cell.id}>
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </TableCell>
                ))}
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  )
}
