'use client'

import {
  useReactTable,
  getCoreRowModel,
  flexRender,
  type ColumnDef,
} from '@tanstack/react-table'
import { useRouter } from 'next/navigation'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { IconEye, IconTrash, IconRobot } from '@tabler/icons-react'

export interface WeeklyReportRow {
  id: string
  studentId: string | null
  studentName: string | null
  weekStart: string | null
  weekEnd: string | null
  summaryText: string | null
  autoGenerated: boolean | null
  isPublished: boolean | null
  createdAt: Date | null
}

interface WeeklyReportTableProps {
  data: WeeklyReportRow[]
  onDelete: (id: string) => void
}

export function WeeklyReportTable({ data, onDelete }: WeeklyReportTableProps) {
  const router = useRouter()

  const columns: ColumnDef<WeeklyReportRow>[] = [
    {
      accessorKey: 'studentName',
      header: 'Siswa',
      cell: ({ row }) => (
        <span className="font-medium">{row.original.studentName ?? '—'}</span>
      ),
    },
    {
      id: 'period',
      header: 'Periode',
      cell: ({ row }) => (
        <span className="text-sm tabular-nums">
          {row.original.weekStart} – {row.original.weekEnd}
        </span>
      ),
    },
    {
      id: 'status',
      header: 'Status',
      cell: ({ row }) => (
        <div className="flex items-center gap-1.5">
          <Badge variant={row.original.isPublished ? 'default' : 'outline'}>
            {row.original.isPublished ? 'Terbit' : 'Draf'}
          </Badge>
          {row.original.autoGenerated && (
            <Badge variant="secondary" className="gap-1 text-[10px]">
              <IconRobot size={10} />
              AI
            </Badge>
          )}
        </div>
      ),
    },
    {
      id: 'summary',
      header: 'Ringkasan',
      cell: ({ row }) => (
        <span className="text-sm text-muted-foreground line-clamp-1 max-w-xs">
          {row.original.summaryText
            ? row.original.summaryText.slice(0, 80) + (row.original.summaryText.length > 80 ? '…' : '')
            : <em>Belum ada ringkasan</em>}
        </span>
      ),
    },
    {
      id: 'actions',
      header: '',
      cell: ({ row }) => (
        <div className="flex items-center justify-end gap-1">
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8"
            onClick={() => router.push(`/teacher/report/weekly/${row.original.id}`)}
            title="Lihat laporan"
          >
            <IconEye size={16} />
          </Button>
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive hover:text-destructive" title="Hapus laporan">
                <IconTrash size={16} />
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Hapus laporan?</AlertDialogTitle>
                <AlertDialogDescription>
                  Laporan minggu {row.original.weekStart} – {row.original.weekEnd} untuk{' '}
                  <strong>{row.original.studentName}</strong> akan dihapus permanen.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Batal</AlertDialogCancel>
                <AlertDialogAction
                  className="bg-destructive hover:bg-destructive/90"
                  onClick={() => onDelete(row.original.id)}
                >
                  Hapus
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      ),
    },
  ]

  const table = useReactTable({
    data,
    columns,
    getCoreRowModel: getCoreRowModel(),
  })

  if (data.length === 0) {
    return (
      <div className="rounded-md border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Siswa</TableHead>
              <TableHead>Periode</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Ringkasan</TableHead>
              <TableHead />
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell colSpan={5} className="text-center py-12 text-muted-foreground">
                Belum ada laporan untuk periode ini
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </div>
    )
  }

  return (
    <div className="rounded-md border">
      <Table>
        <TableHeader>
          {table.getHeaderGroups().map((hg) => (
            <TableRow key={hg.id}>
              {hg.headers.map((h) => (
                <TableHead key={h.id}>
                  {flexRender(h.column.columnDef.header, h.getContext())}
                </TableHead>
              ))}
            </TableRow>
          ))}
        </TableHeader>
        <TableBody>
          {table.getRowModel().rows.map((row) => (
            <TableRow key={row.id} className="cursor-pointer hover:bg-muted/40">
              {row.getVisibleCells().map((cell) => (
                <TableCell key={cell.id}>
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </TableCell>
              ))}
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  )
}
