'use client'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import {
  IconUsers,
  IconSparkles,
  IconLoader2,
  IconCheck,
} from '@tabler/icons-react'
import type { WeeklyReport } from '@/lib/types/weekly-report-detail'

interface WeeklyReportSummaryProps {
  report: WeeklyReport
  isEditing: boolean
  summaryText: string
  saving: boolean
  onSummaryChange: (v: string) => void
  onSave: () => void
  onCancelEdit: () => void
}

export function WeeklyReportSummary({
  report,
  isEditing,
  summaryText,
  saving,
  onSummaryChange,
  onSave,
  onCancelEdit,
}: WeeklyReportSummaryProps) {
  const isPublished = report.isPublished ?? false

  return (
    <Card>
      <CardHeader className="border-b">
        <CardTitle className="flex items-center gap-2 text-base justify-between">
          <span className="flex items-center gap-2">
            <IconUsers size={18} />
            Ringkasan Pencapaian Mingguan
          </span>
          <div className="flex items-center gap-2 print:hidden">
            {report.autoGenerated && (
              <Badge variant="secondary" className="gap-1 text-[10px]">
                <IconSparkles size={10} />
                AI
              </Badge>
            )}
            <Badge variant={isPublished ? 'default' : 'outline'} className="text-xs">
              {isPublished ? 'Terbit' : 'Draf'}
            </Badge>
          </div>
        </CardTitle>
      </CardHeader>
      <CardContent className="pt-4 space-y-3">
        {isEditing ? (
          <>
            <Textarea
              value={summaryText}
              onChange={(e) => onSummaryChange(e.target.value)}
              rows={10}
              placeholder="Tulis ringkasan perkembangan mingguan siswa..."
              className="text-sm"
            />
            <div className="flex gap-2 print:hidden">
              <Button size="sm" onClick={onSave} disabled={saving} className="gap-1.5">
                {saving ? (
                  <IconLoader2 size={14} className="animate-spin" />
                ) : (
                  <IconCheck size={14} />
                )}
                Simpan
              </Button>
              <Button size="sm" variant="outline" onClick={onCancelEdit}>
                Batal
              </Button>
            </div>
          </>
        ) : (
          <div className="space-y-3">
            {report.summaryText ? (
              <p className="text-sm leading-relaxed whitespace-pre-wrap">{report.summaryText}</p>
            ) : (
              <p className="text-sm text-muted-foreground italic">
                Belum ada ringkasan. Klik &quot;Edit Ringkasan&quot; atau &quot;Regenerate AI&quot; untuk membuat.
              </p>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  )
}
