'use client'

import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { IconSparkles, IconLoader2, IconCheck, IconEye, IconEyeOff } from '@tabler/icons-react'

interface WeeklyReport {
  id: string
  studentId: string | null
  weekStart: string | null
  weekEnd: string | null
  summaryText: string | null
  autoGenerated: boolean | null
  isPublished: boolean | null
  createdAt: Date | null
}

interface WeeklyReportFormProps {
  report: WeeklyReport
  studentName: string
  onSave: (summaryText: string) => Promise<void>
  onPublish: (isPublished: boolean) => Promise<void>
  onGenerateAI: () => Promise<string>
}

export function WeeklyReportForm({
  report,
  studentName,
  onSave,
  onPublish,
  onGenerateAI,
}: WeeklyReportFormProps) {
  const [text, setText] = useState(report.summaryText ?? '')
  const [saving, setSaving] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [publishing, setPublishing] = useState(false)
  const [showPublishConfirm, setShowPublishConfirm] = useState(false)
  const [showUnpublishConfirm, setShowUnpublishConfirm] = useState(false)
  const [saved, setSaved] = useState(false)

  const handleSave = async () => {
    setSaving(true)
    setSaved(false)
    try {
      await onSave(text)
      setSaved(true)
      setTimeout(() => setSaved(false), 2000)
    } finally {
      setSaving(false)
    }
  }

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      const summary = await onGenerateAI()
      setText(summary)
    } finally {
      setGenerating(false)
    }
  }

  const handlePublish = async (publish: boolean) => {
    setPublishing(true)
    try {
      await onPublish(publish)
    } finally {
      setPublishing(false)
      setShowPublishConfirm(false)
      setShowUnpublishConfirm(false)
    }
  }

  const weekLabel =
    report.weekStart && report.weekEnd
      ? `${report.weekStart} – ${report.weekEnd}`
      : '—'

  return (
    <>
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center justify-between text-base">
            <span>
              📝 Laporan Mingguan — {studentName}
              <span className="ml-2 text-sm text-muted-foreground font-normal">({weekLabel})</span>
            </span>
            <Badge variant={report.isPublished ? 'default' : 'outline'}>
              {report.isPublished ? '✓ Dipublikasi' : 'Draf'}
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-1">
            <div className="flex items-center justify-between">
              <Label>Isi Laporan</Label>
              <Button
                variant="outline"
                size="sm"
                onClick={handleGenerate}
                disabled={generating}
                className="gap-1.5"
              >
                {generating ? (
                  <IconLoader2 size={14} className="animate-spin" />
                ) : (
                  <IconSparkles size={14} />
                )}
                {generating ? 'Membuat draft AI...' : 'Buat dengan AI'}
              </Button>
            </div>
            <Textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              rows={14}
              placeholder="Tulis laporan mingguan atau klik 'Buat dengan AI' untuk membuat draft otomatis..."
              className="font-mono text-sm"
            />
          </div>

          <div className="flex gap-2 justify-between">
            <Button
              onClick={handleSave}
              disabled={saving || saved}
              className="gap-1.5"
            >
              {saving ? (
                <IconLoader2 size={14} className="animate-spin" />
              ) : saved ? (
                <IconCheck size={14} />
              ) : null}
              {saved ? 'Tersimpan' : saving ? 'Menyimpan...' : 'Simpan'}
            </Button>

            <div className="flex gap-2">
              {report.isPublished ? (
                <Button
                  variant="outline"
                  onClick={() => setShowUnpublishConfirm(true)}
                  disabled={publishing}
                  className="gap-1.5"
                >
                  <IconEyeOff size={14} />
                  Batalkan Publikasi
                </Button>
              ) : (
                <Button
                  variant="default"
                  onClick={() => setShowPublishConfirm(true)}
                  disabled={publishing || !text.trim()}
                  className="gap-1.5"
                >
                  <IconEye size={14} />
                  Publikasikan ke Orang Tua
                </Button>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Publish confirm */}
      <AlertDialog open={showPublishConfirm} onOpenChange={setShowPublishConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Publikasikan laporan?</AlertDialogTitle>
            <AlertDialogDescription>
              Laporan mingguan {studentName} untuk minggu {weekLabel} akan terlihat oleh orang tua.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Batal</AlertDialogCancel>
            <AlertDialogAction onClick={() => handlePublish(true)}>Publikasikan</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Unpublish confirm */}
      <AlertDialog open={showUnpublishConfirm} onOpenChange={setShowUnpublishConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Batalkan publikasi?</AlertDialogTitle>
            <AlertDialogDescription>
              Laporan ini tidak akan terlihat oleh orang tua hingga dipublikasikan kembali.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Batal</AlertDialogCancel>
            <AlertDialogAction onClick={() => handlePublish(false)}>Batalkan Publikasi</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  )
}
