'use client'

import { useState, useRef } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { IconSparkles, IconLoader2, IconCheck, IconEye, IconEyeOff, IconDownload } from '@tabler/icons-react'

interface WeeklyReport {
  id: string
  studentId: string | null
  weekStart: string | null
  weekEnd: string | null
  summaryText: string | null
  autoGenerated: boolean | null
  isPublished: boolean | null
  pdfUrl?: string | null
  createdAt: Date | null
}

interface WeeklyReportFormProps {
  report: WeeklyReport
  studentName: string
  /** Optional ref pointing to the full report DOM node to capture for PDF.
   *  Falls back to the form card itself. */
  printTargetRef?: React.RefObject<HTMLElement>
  onSave: (summaryText: string) => Promise<void>
  onPublish: (isPublished: boolean) => Promise<void>
  onGenerateAI: () => Promise<string>
}

export function WeeklyReportForm({
  report,
  studentName,
  printTargetRef,
  onSave,
  onPublish,
  onGenerateAI,
}: WeeklyReportFormProps) {
  const cardRef = useRef<HTMLDivElement>(null)
  const [text, setText] = useState(report.summaryText ?? '')
  const [saving, setSaving] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [publishing, setPublishing] = useState(false)
  const [uploadingPdf, setUploadingPdf] = useState(false)
  const [pdfUrl, setPdfUrl] = useState<string | null>(report.pdfUrl ?? null)
  const [showPublishConfirm, setShowPublishConfirm] = useState(false)
  const [showUnpublishConfirm, setShowUnpublishConfirm] = useState(false)
  const [saved, setSaved] = useState(false)

  const buildPdfBuffer = async (): Promise<ArrayBuffer | null> => {
    const targetEl = (printTargetRef?.current ?? cardRef.current) as HTMLElement | null
    if (!targetEl) return null

    const bodyEl = document.body
    const mainEl = document.querySelector('main') as HTMLElement | null
    const prev = {
      bodyOverflow: bodyEl.style.overflow,
      bodyHeight: bodyEl.style.height,
      mainOverflow: mainEl?.style.overflow ?? '',
      mainOverflowY: mainEl?.style.overflowY ?? '',
      mainHeight: mainEl?.style.height ?? '',
    }

    bodyEl.style.overflow = 'visible'
    bodyEl.style.height = 'auto'
    if (mainEl) {
      mainEl.style.overflow = 'visible'
      mainEl.style.overflowY = 'visible'
      mainEl.style.height = 'auto'
    }

    try {
      const html2canvas = (await import('html2canvas')).default
      const { jsPDF } = await import('jspdf')

      const onclone = (_clonedDoc: Document, clonedEl: HTMLElement) => {
        const doc = clonedEl.ownerDocument

        doc.querySelectorAll<HTMLLinkElement>('link[rel="stylesheet"]').forEach(el => el.remove())

        doc.querySelectorAll('style').forEach(el => {
          if (!el.textContent) return
          el.textContent = el.textContent
            .replace(/:\s*oklch\([^;{}]+\)/g, ': transparent')
            .replace(/:\s*lab\([^;{}]+\)/g, ': transparent')
            .replace(/:\s*lch\([^;{}]+\)/g, ': transparent')
            .replace(/:\s*color-mix\([^;{}]+\)/g, ': transparent')
        })

        const style = doc.createElement('style')
        style.textContent = `
          :root {
            --background: #f9f9fe !important;
            --foreground: #292933 !important;
            --card: #ffffff !important;
            --card-foreground: #292933 !important;
            --popover: #ffffff !important;
            --popover-foreground: #292933 !important;
            --primary-foreground: #fcfcfc !important;
            --secondary-foreground: #292933 !important;
            --muted: #f3f3f8 !important;
            --muted-foreground: #737382 !important;
            --accent-foreground: #fcfcfc !important;
            --destructive: #db4141 !important;
            --border: #e3e3e9 !important;
            --input: #eeeef5 !important;
            --ring: #3f52b2 !important;
            --sidebar: #3f52b2 !important;
            --sidebar-foreground: #fcfcfc !important;
          }
        `
        doc.head.appendChild(style)
      }

      const canvas = await html2canvas(targetEl, {
        scale: 2,
        useCORS: true,
        logging: false,
        scrollX: 0,
        scrollY: 0,
        windowWidth: targetEl.scrollWidth,
        windowHeight: targetEl.scrollHeight,
        onclone,
      })

      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
      const pdfWidth = pdf.internal.pageSize.getWidth()
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width
      const pageHeight = pdf.internal.pageSize.getHeight()

      let heightLeft = pdfHeight
      let position = 0
      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight)
      heightLeft -= pageHeight
      while (heightLeft > 0) {
        position -= pageHeight
        pdf.addPage()
        pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, pdfHeight)
        heightLeft -= pageHeight
      }

      return pdf.output('arraybuffer')
    } finally {
      bodyEl.style.overflow = prev.bodyOverflow
      bodyEl.style.height = prev.bodyHeight
      if (mainEl) {
        mainEl.style.overflow = prev.mainOverflow
        mainEl.style.overflowY = prev.mainOverflowY
        mainEl.style.height = prev.mainHeight
      }
    }
  }

  const handleSave = async () => {
    setSaving(true)
    setSaved(false)
    try {
      await onSave(text)
      setSaved(true)
      setTimeout(() => setSaved(false), 2000)
    } finally {
      setSaving(false)
    }
  }

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      const summary = await onGenerateAI()
      setText(summary)
    } finally {
      setGenerating(false)
    }
  }

  const handlePublish = async (publish: boolean) => {
    setPublishing(true)
    try {
      await onPublish(publish)

      if (publish) {
        setUploadingPdf(true)
        try {
          const buffer = await buildPdfBuffer()
          if (buffer) {
            const blob = new Blob([buffer], { type: 'application/pdf' })
            const form = new FormData()
            form.append('file', blob, `laporan_mingguan_${report.id}.pdf`)
            const res = await fetch(`/api/reports/weekly/${report.id}/pdf`, {
              method: 'POST',
              body: form,
            })
            const json = await res.json()
            if (res.ok && json.pdfUrl) {
              setPdfUrl(json.pdfUrl)
            }
          }
        } catch (e) {
          console.error('PDF upload failed:', e)
        } finally {
          setUploadingPdf(false)
        }
      }
    } finally {
      setPublishing(false)
      setShowPublishConfirm(false)
      setShowUnpublishConfirm(false)
    }
  }

  const weekLabel =
    report.weekStart && report.weekEnd
      ? `${report.weekStart} – ${report.weekEnd}`
      : '—'

  return (
    <>
      <Card ref={cardRef}>
        <CardHeader className="pb-3">
          <CardTitle className="flex items-center justify-between text-base">
            <span>
              Laporan Mingguan — {studentName}
              <span className="ml-2 text-sm text-muted-foreground font-normal">({weekLabel})</span>
            </span>
            <Badge variant={report.isPublished ? 'default' : 'outline'}>
              {report.isPublished ? '✓ Dipublikasi' : 'Draf'}
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-1">
            <div className="flex items-center justify-between">
              <Label>Isi Laporan</Label>
              <Button
                variant="outline"
                size="sm"
                onClick={handleGenerate}
                disabled={generating}
                className="gap-1.5"
              >
                {generating ? (
                  <IconLoader2 size={14} className="animate-spin" />
                ) : (
                  <IconSparkles size={14} />
                )}
                {generating ? 'Membuat draft AI...' : 'Buat dengan AI'}
              </Button>
            </div>
            <Textarea
              value={text}
              onChange={(e) => setText(e.target.value)}
              rows={14}
              placeholder="Tulis laporan mingguan atau klik 'Buat dengan AI' untuk membuat draft otomatis..."
              className="font-mono text-sm"
            />
          </div>

          <div className="flex gap-2 justify-between">
            <Button
              onClick={handleSave}
              disabled={saving || saved}
              className="gap-1.5"
            >
              {saving ? (
                <IconLoader2 size={14} className="animate-spin" />
              ) : saved ? (
                <IconCheck size={14} />
              ) : null}
              {saved ? 'Tersimpan' : saving ? 'Menyimpan...' : 'Simpan'}
            </Button>

            <div className="flex gap-2">
              {pdfUrl && (
                <Button variant="outline" size="sm" asChild className="gap-1.5">
                  <a href={pdfUrl} target="_blank" rel="noopener noreferrer">
                    <IconDownload size={14} />
                    Unduh PDF
                  </a>
                </Button>
              )}
              {uploadingPdf && !pdfUrl && (
                <Button variant="outline" size="sm" disabled className="gap-1.5">
                  <IconLoader2 size={14} className="animate-spin" />
                  Membuat PDF...
                </Button>
              )}
              {report.isPublished ? (
                <Button
                  variant="outline"
                  onClick={() => setShowUnpublishConfirm(true)}
                  disabled={publishing}
                  className="gap-1.5"
                >
                  <IconEyeOff size={14} />
                  Batalkan Publikasi
                </Button>
              ) : (
                <Button
                  variant="default"
                  onClick={() => setShowPublishConfirm(true)}
                  disabled={publishing || !text.trim()}
                  className="gap-1.5"
                >
                  <IconEye size={14} />
                  Publikasikan ke Orang Tua
                </Button>
              )}
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Publish confirm */}
      <AlertDialog open={showPublishConfirm} onOpenChange={setShowPublishConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Publikasikan laporan?</AlertDialogTitle>
            <AlertDialogDescription>
              Laporan mingguan {studentName} untuk minggu {weekLabel} akan terlihat oleh orang tua.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Batal</AlertDialogCancel>
            <AlertDialogAction onClick={() => handlePublish(true)}>Publikasikan</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Unpublish confirm */}
      <AlertDialog open={showUnpublishConfirm} onOpenChange={setShowUnpublishConfirm}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Batalkan publikasi?</AlertDialogTitle>
            <AlertDialogDescription>
              Laporan ini tidak akan terlihat oleh orang tua hingga dipublikasikan kembali.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Batal</AlertDialogCancel>
            <AlertDialogAction onClick={() => handlePublish(false)}>Batalkan Publikasi</AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  )
}
