// ── Types for Weekly Report Detail ──────────────────────────────────────────

export interface WeeklyReport {
  id: string
  studentId: string | null
  weekStart: string | null
  weekEnd: string | null
  summaryText: string | null
  autoGenerated: boolean | null
  isPublished: boolean | null
  pdfUrl: string | null
  sentAt: Date | null
  createdAt: Date | null
}

export interface StudentInfo {
  id: string
  fullName: string | null
  birthDate: string | null
  gender: string | null
  classroomId: string | null
}

export interface TopicsPayload {
  semester: { title: string; academicYear: string | null; semesterNumber: number | null } | null
  monthly: { title: string; monthNumber: number | null } | null
  weekly: { title: string; weekNumber: number | null } | null
}

export interface AttendanceDay {
  date: string
  checkIn: { status: string | null; mood: string | null } | null
  checkOut: { status: string | null; mood: string | null } | null
}

export interface ScopeScores {
  [scope: string]: { BB: number; MB: number; BSH: number; BSB: number; total: number }
}

export interface MoodTimeSeriesItem {
  date: string
  checkIn: string | null
  checkOut: string | null
}

export interface ScopeBreakdown {
  scope: string
  objectives: {
    objectiveId: string | null
    objectiveDescription: string | null
    entries: {
      date: string | null
      activityContext: string | null
      score: string | null
      note: string | null
    }[]
  }[]
}

export interface ActivityImage {
  date: string | null
  imageUrl: string | null
}

export interface TeacherInfo {
  id: string
  name: string | null
}

export interface DetailPayload {
  report: WeeklyReport
  student: StudentInfo | null
  topics: TopicsPayload | null
  attendanceByDate: AttendanceDay[]
  scopeScores: ScopeScores
  moodTimeSeries: MoodTimeSeriesItem[]
  scopeBreakdown: ScopeBreakdown[]
  activityImages: ActivityImage[]
  teachers: TeacherInfo[]
}

// ── Constants ────────────────────────────────────────────────────────────────

export const MOOD_LABELS: Record<string, string> = {
  bahagia: '😊 Bahagia',
  sedih: '😢 Sedih',
  marah: '😠 Marah',
  takut: '😨 Takut',
  jijik: '🤢 Jijik',
}

export const STATUS_LABELS: Record<string, string> = {
  present: 'Hadir',
  sick: 'Sakit',
  permission: 'Izin',
}

export const STATUS_COLORS: Record<string, string> = {
  present: 'bg-green-100 text-green-700',
  sick: 'bg-red-100 text-red-700',
  permission: 'bg-yellow-100 text-yellow-700',
}

export const MONTH_NAMES = [
  'Januari','Februari','Maret','April','Mei','Juni',
  'Juli','Agustus','September','Oktober','November','Desember',
]
