'use client'

import { useState, useEffect } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { PageHeader } from '@/components/layout/page-header'
import { LoadingState } from '@/components/layout/loading-state'
import { WeeklyReportForm } from '@/components/report/weekly-report-form'
import { useCurrentUser } from '@/lib/hooks/use-current-user'
import {
  IconChartBar,
  IconHome,
  IconLoader2,
  IconPlus,
} from '@tabler/icons-react'
import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Badge } from '@/components/ui/badge'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { format, startOfWeek, endOfWeek } from 'date-fns'

interface Student {
  id: string
  fullName: string | null
  classroomId: string | null
}

interface WeeklyReport {
  id: string
  studentId: string | null
  weekStart: string | null
  weekEnd: string | null
  summaryText: string | null
  autoGenerated: boolean | null
  isPublished: boolean | null
  createdAt: Date | null
}

export default function TeacherWeeklyReportPage() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const { user, classrooms, loading: userLoading } = useCurrentUser()

  const [students, setStudents] = useState<Student[]>([])
  const [selectedStudentId, setSelectedStudentId] = useState<string>(searchParams.get('studentId') ?? '')
  const [reports, setReports] = useState<WeeklyReport[]>([])
  const [selectedReport, setSelectedReport] = useState<WeeklyReport | null>(null)
  const [loadingStudents, setLoadingStudents] = useState(false)
  const [loadingReports, setLoadingReports] = useState(false)
  const [creating, setCreating] = useState(false)
  const [newWeekStart, setNewWeekStart] = useState(format(startOfWeek(new Date(), { weekStartsOn: 1 }), 'yyyy-MM-dd'))
  const [newWeekEnd, setNewWeekEnd] = useState(format(endOfWeek(new Date(), { weekStartsOn: 1 }), 'yyyy-MM-dd'))

  useEffect(() => {
    if (!userLoading && !user) router.push('/auth/login')
    if (!userLoading && user && user.role !== 'teacher') router.push('/unauthorized')
  }, [user, userLoading, router])

  // Fetch students in teacher's classroom
  useEffect(() => {
    const classroomId = classrooms?.[0]?.id
    if (!classroomId) return
    setLoadingStudents(true)
    fetch(`/api/students?classroomId=${classroomId}`)
      .then((r) => r.json())
      .then((data) => setStudents(data.data ?? []))
      .catch(console.error)
      .finally(() => setLoadingStudents(false))
  }, [classrooms])

  // Fetch reports when student selected
  useEffect(() => {
    if (!selectedStudentId) return
    setLoadingReports(true)
    setSelectedReport(null)
    fetch(`/api/reports/weekly?studentId=${selectedStudentId}`)
      .then((r) => r.json())
      .then((data) => setReports(data.data ?? []))
      .catch(console.error)
      .finally(() => setLoadingReports(false))
  }, [selectedStudentId])

  const handleCreateReport = async () => {
    if (!selectedStudentId) return
    setCreating(true)
    try {
      const res = await fetch('/api/reports/weekly', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          studentId: selectedStudentId,
          weekStart: newWeekStart,
          weekEnd: newWeekEnd,
        }),
      })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error)
      setReports((prev) => [json.data, ...prev])
      setSelectedReport(json.data)
    } catch (err) {
      console.error(err)
    } finally {
      setCreating(false)
    }
  }

  const handleSave = async (summaryText: string) => {
    if (!selectedReport) return
    const res = await fetch(`/api/reports/weekly/${selectedReport.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ summaryText }),
    })
    const json = await res.json()
    if (!res.ok) throw new Error(json.error)
    setSelectedReport(json.data)
    setReports((prev) => prev.map((r) => (r.id === json.data.id ? json.data : r)))
  }

  const handlePublish = async (isPublished: boolean) => {
    if (!selectedReport) return
    const res = await fetch(`/api/reports/weekly/${selectedReport.id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ isPublished }),
    })
    const json = await res.json()
    if (!res.ok) throw new Error(json.error)
    setSelectedReport(json.data)
    setReports((prev) => prev.map((r) => (r.id === json.data.id ? json.data : r)))
  }

  const handleGenerateAI = async () => {
    if (!selectedReport || !selectedStudentId) throw new Error('Pilih laporan terlebih dahulu')
    const res = await fetch('/api/reports/weekly/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        studentId: selectedStudentId,
        weekStart: selectedReport.weekStart,
        weekEnd: selectedReport.weekEnd,
      }),
    })
    const json = await res.json()
    if (!res.ok) throw new Error(json.error)
    return json.summary as string
  }

  if (userLoading) return <LoadingState message="Memuat data..." />
  if (!user) return null

  const selectedStudent = students.find((s) => s.id === selectedStudentId)

  return (
    <div className="space-y-6">
      <PageHeader
        title="Laporan Mingguan Siswa"
        description="Buat dan kelola laporan mingguan untuk dikirim ke orang tua"
        breadcrumbs={[
          { label: 'Beranda', href: '/teacher', icon: IconHome },
          { label: 'Laporan', href: '/teacher/report', icon: IconChartBar },
          { label: 'Laporan Mingguan' },
        ]}
      />

      <div className="grid gap-4 lg:grid-cols-[300px_1fr]">
        {/* Left: Student + report selector */}
        <div className="space-y-4">
          <Card>
            <CardContent className="pt-4 space-y-4">
              <div className="space-y-1.5">
                <Label>Pilih Siswa</Label>
                {loadingStudents ? (
                  <div className="flex items-center gap-2 text-muted-foreground text-sm">
                    <IconLoader2 size={14} className="animate-spin" /> Memuat...
                  </div>
                ) : (
                  <Select value={selectedStudentId} onValueChange={setSelectedStudentId}>
                    <SelectTrigger>
                      <SelectValue placeholder="Pilih siswa..." />
                    </SelectTrigger>
                    <SelectContent>
                      {students.map((s) => (
                        <SelectItem key={s.id} value={s.id}>
                          {s.fullName ?? '—'}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                )}
              </div>

              {selectedStudentId && (
                <div className="space-y-3">
                  <div className="border-t pt-3 space-y-2">
                    <Label className="text-xs text-muted-foreground">Buat laporan baru</Label>
                    <div className="grid grid-cols-2 gap-2">
                      <div className="space-y-1">
                        <Label className="text-xs">Mulai</Label>
                        <Input
                          type="date"
                          value={newWeekStart}
                          onChange={(e) => setNewWeekStart(e.target.value)}
                          className="text-xs"
                        />
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs">Selesai</Label>
                        <Input
                          type="date"
                          value={newWeekEnd}
                          onChange={(e) => setNewWeekEnd(e.target.value)}
                          className="text-xs"
                        />
                      </div>
                    </div>
                    <Button
                      size="sm"
                      className="w-full gap-1"
                      onClick={handleCreateReport}
                      disabled={creating}
                    >
                      {creating ? (
                        <IconLoader2 size={14} className="animate-spin" />
                      ) : (
                        <IconPlus size={14} />
                      )}
                      Buat Laporan
                    </Button>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>

          {/* Report list */}
          {selectedStudentId && (
            <Card>
              <CardContent className="pt-4 space-y-2">
                <p className="text-xs font-medium text-muted-foreground uppercase tracking-wider">
                  Riwayat Laporan
                </p>
                {loadingReports ? (
                  <div className="flex items-center gap-2 text-muted-foreground text-sm">
                    <IconLoader2 size={14} className="animate-spin" /> Memuat...
                  </div>
                ) : reports.length === 0 ? (
                  <p className="text-sm text-muted-foreground">Belum ada laporan</p>
                ) : (
                  <div className="space-y-1.5 max-h-[400px] overflow-y-auto">
                    {reports.map((r) => (
                      <button
                        key={r.id}
                        onClick={() => setSelectedReport(r)}
                        className={`w-full text-left p-2.5 rounded-md border text-xs transition-colors ${
                          selectedReport?.id === r.id
                            ? 'bg-primary text-primary-foreground border-primary'
                            : 'hover:bg-muted'
                        }`}
                      >
                        <div className="flex items-center justify-between gap-1">
                          <span className="font-medium">
                            {r.weekStart} – {r.weekEnd}
                          </span>
                          <Badge
                            variant={r.isPublished ? 'default' : 'outline'}
                            className="text-[10px] px-1.5 py-0"
                          >
                            {r.isPublished ? '✓' : 'Draf'}
                          </Badge>
                        </div>
                      </button>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          )}
        </div>

        {/* Right: Form */}
        <div>
          {!selectedStudentId && (
            <Card>
              <CardContent className="py-16 text-center text-muted-foreground">
                Pilih siswa untuk mulai mengelola laporan mingguan
              </CardContent>
            </Card>
          )}
          {selectedStudentId && !selectedReport && (
            <Card>
              <CardContent className="py-16 text-center text-muted-foreground">
                Pilih laporan dari daftar atau buat laporan baru
              </CardContent>
            </Card>
          )}
          {selectedReport && (
            <WeeklyReportForm
              key={selectedReport.id}
              report={selectedReport}
              studentName={selectedStudent?.fullName ?? 'Siswa'}
              onSave={handleSave}
              onPublish={handlePublish}
              onGenerateAI={handleGenerateAI}
            />
          )}
        </div>
      </div>
    </div>
  )
}
